fix: improve error handling and output for application and virtual host ID extraction in CI workflow

diff --git a/.github/workflows/ci-clean-preview-application.yml b/.github/workflows/ci-clean-preview-application.yml
--- a/.github/workflows/ci-clean-preview-application.yml
+++ b/.github/workflows/ci-clean-preview-application.yml
@@ -46,12 +46,17 @@ jobs:
             - name: Extract Application ID
               id: extract-application-id
               run: |
-                  APP_ID=$(echo '${{ steps.list-applications.outputs.response }}' | jq -r '.[] | select(.name == "pr-${{ github.event.number }}-preview") | .id')
-                  if [ -z "$APP_ID" ]; then
-                    echo "APPLICATION_ID not found."
-                    exit 0
+                  app_id=$(jq -r '.[] | select(.name == "pr-${{ github.event.number }}-preview") | .id' <<<"${{ steps.list-applications.outputs.response }}" || {
+                    echo "Error parsing JSON response" >&2
+                    exit 1
+                  })
+
+                  if [ -n "$app_id" ]; then
+                    printf '%s=%s\n' 'APPLICATION_ID' "$app_id" >> "$GITHUB_OUTPUT"
+                  else
+                    echo "Application ID not found" >&2
+                    exit 1
                   fi
-                  echo "APPLICATION_ID=$APP_ID" >> $GITHUB_OUTPUT
 
             - name: Delete Preview Application
               if: steps.extract-application-id.outputs.APPLICATION_ID != ''
@@ -92,12 +97,17 @@ jobs:
             - name: Extract Virtual Host ID
               id: extract-vhost-id
               run: |
-                  VHOST_ID=$(echo '${{ steps.list-virtual-hosts.outputs.response }}' | jq -r '.[] | select(.name == "${{ steps.parse-server-data.outputs.SERVER_IP }}:6969") | .id')
-                  if [ -z "$VHOST_ID" ]; then
-                    echo "VIRTUAL_HOST_ID not found."
-                    exit 0
+                  vhost_id=$(jq -r '.[] | select(.name == "pr-${{ github.event.number }}-preview") | .id' <<<"${{ steps.list-virtual-hosts.outputs.response }}" || {
+                    echo "Error parsing JSON response" >&2
+                    exit 1
+                  })
+
+                  if [ -n "$vhost_id" ]; then
+                    printf '%s=%s\n' 'VIRTUAL_HOST_ID' "$vhost_id" >> "$GITHUB_OUTPUT"
+                  else
+                    echo "Virtual Host ID not found" >&2
+                    exit 1
                   fi
-                  echo "VIRTUAL_HOST_ID=$VHOST_ID" >> $GITHUB_OUTPUT
 
             - name: Delete Preview Virtual Host
               if: steps.extract-vhost-id.outputs.VIRTUAL_HOST_ID != ''
